### ISSUE TITLE
DTS bundler exports internal schema_d_exports as t and imports .d.mts in runtime .mjs files with multi-entry configs

### ISSUE THREAD

**Issue by agcty** [sxzz/tsdown#718]
## Description

When using tsdown with multiple entry points that contain `export * from` re-exports, the DTS bundler:

1. Exports an internal namespace `schema_d_exports as t` in the generated `.d.mts` files
2. Imports from `.d.mts` declaration files in runtime `.mjs` files (causing runtime errors)

This worked correctly in v0.16.8 but broke in v0.18.x+.

## Reproduction

**tsdown.config.ts:**
```typescript
import { defineConfig } from "tsdown"

export default defineConfig({
  entry: ["src/index.ts", "src/schema.ts"],
  format: ["esm"],
  dts: true,
  clean: true,
})
```

**src/schema.ts:**
```typescript
export * from "./core/schema"
export * from "./user/schema"
```

**src/core/schema.ts:**
```typescript
export const coreTable = { name: "core" }
```

**src/user/schema.ts:**
```typescript
export const userTable = { name: "user" }
```

## Expected behavior (v0.16.8)

**dist/schema.d.mts:**
```typescript
import { c as coreTable } from "./schema-abc123.mjs";
import { u as userTable } from "./schema-def456.mjs";
export { coreTable, userTable };
```

Clean exports, imports from `.mjs` files.

## Actual behavior (v0.18.4, v0.19.0, v0.20.0-beta.3)

**dist/schema.d.mts:**
```typescript
// ... bundled content ...
export { coreTable, userTable, schema_d_exports as t };
```

**dist/index.mjs:**
```typescript
import { o as __exportAll } from "./schema-abc123.d.mts";  // imports .d.mts in runtime!
```

Issues:
1. `schema_d_exports as t` leaks internal namespace, causing TypeScript errors when multiple packages with this pattern are re-exported together
2. Runtime `.mjs` imports from `.d.mts` declaration files, causing `TypeError: (0, x.o) is not a function`

## Environment

- tsdown: 0.18.4 / 0.19.0 / 0.20.0-beta.3 (broken)
- tsdown: 0.16.8 (works)
- Node: v22.x
- OS: macOS

## Workaround

Downgrade to tsdown 0.16.8

**Comment by agcty** [comment]
Closing - filed at the more appropriate repo: https://github.com/sxzz/rolldown-plugin-dts
